steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
# push container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
# deploy container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  #args: ['run', '--filename', 'deployment_service.yaml', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--location', '${_CLOUDSDK_COMPUTE_ZONE}', '--cluster', '${_CLOUDSDK_CONTAINER_CLUSTER}']
  #args: ['run', '--filename', 'deployment_service.yaml', '--location', '${_CLOUDSDK_COMPUTE_ZONE}', '--cluster', '${_CLOUDSDK_CONTAINER_CLUSTER}']
  args: ['run', 'deploy', 'demo-ui', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--cluster', 'cluster-1', '--location', 'us-central1-c', '--namespace', 'default']
