apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test3
  labels:
    app: flask-test3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test3
  template:
    metadata:
      labels:
        app: flask-test3
    spec:
      containers:
        - name: flask-test3
          image: us-west1-docker.pkg.dev/glossy-champion-343401/test/flask-test:1.0
          #imagePullPolicy: Never
          #imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-test3
  namespace: default
  labels:
    app: flask-test3
spec:
  selector:
    app: flask-test3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
  #type: LoadBalancer

