apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test3
  labels:
    app: flask-test3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test3
  template:
    metadata:
      labels:
        app: flask-test3
    spec:
      containers:
        - name: flask-test3
          #image: gcr.io/glossy-champion-343401/gke:latest
          #image: gcr.io/glossy-champion-343401/gke@sha256:3b57fc089fefe366226a413d63d5a8b2b3ed3acb4b08f4ef4cb9e5614b20cd52
          image: gcr.io/$GCLOUD_PROJECT/gke@sha256:3b57fc089fefe366226a413d63d5a8b2b3ed3acb4b08f4ef4cb9e5614b20cd52
          #imagePullPolicy: Never
          #imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-test3
  namespace: default
  labels:
    app: flask-test3
spec:
  selector:
    app: flask-test3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002
  type: NodePort
  #type: LoadBalancer

