apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test2
  labels:
    app: flask-test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test2
  template:
    metadata:
      labels:
        app: flask-test2
    spec:
      containers:
        - name: flask-test2
          image: gcr.io/glossy-champion-343401/gke:latest
---
apiVersion: v1
kind: Service
metadata:
  name: flask-test2
  namespace: default
  labels:
    app: flask-test2
spec:
  selector:
    app: flask-test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
  #type: LoadBalancer

